name: Sync to Google Drive

on:
  push:
    branches:
      - main # jei pagrindinė šaka yra master, pakeiskite į master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Setup Service Account Credentials
        run: |
          echo '${{ secrets.GDRIVE_CREDENTIALS }}' > service_account.json

      - name: Sync files to Google Drive
        run: |
          rclone sync . :drive: \
            --drive-service-account-file=service_account.json \
            --drive-root-folder-id=${{ secrets.GDRIVE_FOLDER_ID }} \
            --drive-scope=drive \
            --exclude ".git/**" \
            --exclude ".github/**" \
            --exclude "service_account.json"
